// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement;

#nullable disable

namespace SchoolManagement.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagement.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Principal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cambridge, MA",
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Harvard University",
                            Principal = "John Smith",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Stanford, CA",
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Stanford University",
                            Principal = "Mary Johnson",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Cambridge, MA",
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MIT",
                            Principal = "Robert Brown",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Oxford, UK",
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oxford University",
                            Principal = "Emily Davis",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Cambridge, UK",
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cambridge University",
                            Principal = "Michael Wilson",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Address = "New Haven, CT",
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Yale University",
                            Principal = "Sarah Miller",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Princeton, NJ",
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Princeton University",
                            Principal = "David Garcia",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Address = "New York, NY",
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Columbia University",
                            Principal = "Jennifer Martinez",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Berkeley, CA",
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "UC Berkeley",
                            Principal = "James Anderson",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Address = "Pasadena, CA",
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Caltech",
                            Principal = "Patricia Taylor",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SchoolManagement.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SchoolId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice.walker@email.com",
                            FullName = "Alice Walker",
                            Phone = "1234567890",
                            SchoolId = 1,
                            StudentId = "STU001",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob.martin@email.com",
                            FullName = "Bob Martin",
                            Phone = "2345678901",
                            SchoolId = 1,
                            StudentId = "STU002",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carol.white@email.com",
                            FullName = "Carol White",
                            Phone = "3456789012",
                            SchoolId = 2,
                            StudentId = "STU003",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "daniel.harris@email.com",
                            FullName = "Daniel Harris",
                            Phone = "4567890123",
                            SchoolId = 2,
                            StudentId = "STU004",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.clark@email.com",
                            FullName = "Emma Clark",
                            Phone = "5678901234",
                            SchoolId = 3,
                            StudentId = "STU005",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "frank.lewis@email.com",
                            FullName = "Frank Lewis",
                            Phone = "6789012345",
                            SchoolId = 3,
                            StudentId = "STU006",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "grace.lee@email.com",
                            FullName = "Grace Lee",
                            Phone = "7890123456",
                            SchoolId = 4,
                            StudentId = "STU007",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "henry.king@email.com",
                            FullName = "Henry King",
                            Phone = "8901234567",
                            SchoolId = 4,
                            StudentId = "STU008",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "iris.moore@email.com",
                            FullName = "Iris Moore",
                            Phone = "9012345678",
                            SchoolId = 5,
                            StudentId = "STU009",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jack.scott@email.com",
                            FullName = "Jack Scott",
                            Phone = "1122334455",
                            SchoolId = 5,
                            StudentId = "STU010",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "karen.young@email.com",
                            FullName = "Karen Young",
                            Phone = "2233445566",
                            SchoolId = 6,
                            StudentId = "STU011",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "leo.allen@email.com",
                            FullName = "Leo Allen",
                            Phone = "3344556677",
                            SchoolId = 6,
                            StudentId = "STU012",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mia.hall@email.com",
                            FullName = "Mia Hall",
                            Phone = "4455667788",
                            SchoolId = 7,
                            StudentId = "STU013",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "noah.adams@email.com",
                            FullName = "Noah Adams",
                            Phone = "5566778899",
                            SchoolId = 7,
                            StudentId = "STU014",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "olivia.baker@email.com",
                            FullName = "Olivia Baker",
                            Phone = "6677889900",
                            SchoolId = 8,
                            StudentId = "STU015",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "paul.carter@email.com",
                            FullName = "Paul Carter",
                            Phone = "7788990011",
                            SchoolId = 8,
                            StudentId = "STU016",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "quinn.nelson@email.com",
                            FullName = "Quinn Nelson",
                            Phone = "8899001122",
                            SchoolId = 9,
                            StudentId = "STU017",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rachel.green@email.com",
                            FullName = "Rachel Green",
                            Phone = "9900112233",
                            SchoolId = 9,
                            StudentId = "STU018",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sam.turner@email.com",
                            FullName = "Sam Turner",
                            Phone = "1011121314",
                            SchoolId = 10,
                            StudentId = "STU019",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tina.phillips@email.com",
                            FullName = "Tina Phillips",
                            Phone = "1112131415",
                            SchoolId = 10,
                            StudentId = "STU020",
                            UpdatedAt = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SchoolManagement.Student", b =>
                {
                    b.HasOne("SchoolManagement.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchoolManagement.School", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
